use_frameworks!

target 'UNDanielBasicTool_Swift_Example' do
  pod 'UNDanielBasicTool_Swift', :path => '../'

  target 'UNDanielBasicTool_Swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
