use_frameworks!

target 'UNDanielBasicTool_Swift_Example' do
  pod 'UNDanielBasicTool_Swift', :path => '../'

  target 'UNDanielBasicTool_Swift_Tests' do
    inherit! :search_paths

    pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
